### PR TITLE
windows平台打包

### PR DESCRIPTION
**Pull request by Shurelol**
附带托盘图标，右键主页，日志，退出。

### CODE REVIEW

**Comment by Shurelol** [comment]
大佬，exe的发布我是照着群辉的写得，两个里面都有创建release的流程。运行的慢的那个可能会卡在那里失败。

**Comment by jxxghp** [comment]
wxpython依赖包无法安装成功，导致镜像包无法构件，我回滚了代码，还要再研究下。
另外，actions应该也不对，我看运行环境还是ubuntu，有些路径也对不上。

**Comment by Shurelol** [comment]
抱歉，actions后面照着群晖改的时候不小心把运行环境也粘贴过去了。
可以看下打包过程
https://github.com/Shurelol/nas-tools/runs/7848356962?check_suite_focus=true

**Comment by Shurelol** [comment]
`name: Nas-tools Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:

    - name: 初始化 Python 3.10.6
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.6'

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install numpy
        pip install -U wheel
        pip install railroad
        pip install wxpython
        git clone https://github.com/Shurelol/nas-tools
        cd nas-tools
        pip install -r requirements.txt
    - name: pyinstaller打包
      run:
        cd nas-tools &&
        copy .\windows\rely\upx.exe c:\hostedtoolcache\windows\python\3.10.6\x64\Scripts &&
        copy .\windows\rely\hook-cn2an.py c:\hostedtoolcache\windows\python\3.10.6\x64\lib\site-packages\pyinstaller\hooks &&
        copy .\windows\rely\hook-zhconv.py c:\hostedtoolcache\windows\python\3.10.6\x64\lib\site-packages\pyinstaller\hooks &&
        xcopy D:\a\nas-tools\nas-tools\nas-tools\web c:\hostedtoolcache\windows\python\3.10.6\x64\lib\site-packages\web\ /e &&
        cd windows &&
        pyinstaller nas-tools.spec &&
        cd dist/

    - name: Create release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: 1.9.21
        release_name: 1.9.21
        body: ${{ github.event.commits[0].message }}
        draft: false
        prerelease: false

    - name: Upload release asset
      id: upload-release-asset
      uses: dwenegar/upload-release-assets@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ steps.create_release.outputs.id }}
        assets_path: D:/a/nas-tools/nas-tools/nas-tools/windows/dist/nas-tools.exe`

**Pull request merged**
